#!/bin/bash

echo "🧹 Cleaning up sensitive files before public commit"
echo ""

# Remove sensitive files from git tracking (if they were previously committed)
echo "📝 Removing sensitive files from git tracking..."
git rm --cached .env.production 2>/dev/null || echo "  ✓ .env.production not tracked"
git rm --cached packages/user-app/.env 2>/dev/null || echo "  ✓ packages/user-app/.env not tracked"
git rm --cached -r backups/ 2>/dev/null || echo "  ✓ backups/ not tracked"
git rm --cached -r infrastructure/cdk.out/ 2>/dev/null || echo "  ✓ infrastructure/cdk.out/ not tracked"
git rm --cached -r terraform/logs/ 2>/dev/null || echo "  ✓ terraform/logs/ not tracked"
git rm --cached -r backend/logs/ 2>/dev/null || echo "  ✓ backend/logs/ not tracked"
git rm --cached -r dev-scripts/ 2>/dev/null || echo "  ✓ dev-scripts/ not tracked"
git rm --cached -r markdown/ 2>/dev/null || echo "  ✓ markdown/ not tracked"

echo ""
echo "✅ Sensitive files removed from git tracking"
echo ""
echo "📋 Files excluded via .gitignore:"
echo "  • .env.production"
echo "  • packages/user-app/.env"
echo "  • backups/"
echo "  • dev-scripts/ (contains account-specific scripts)"
echo "  • markdown/ (contains account-specific docs)"
echo "  • infrastructure/cdk.out/"
echo "  • terraform/logs/"
echo "  • backend/logs/"
echo ""
echo "⚠️  IMPORTANT NEXT STEPS:"
echo ""
echo "1. Create your own .env files from .env.example templates"
echo "2. Commit the changes:"
echo "   git add .gitignore .env.example packages/user-app/.env.example"
echo "   git commit -m 'Add .gitignore for sensitive files and example configs'"
echo ""
echo "3. Verify what will be committed:"
echo "   git status"
echo ""
echo "4. Your dev-scripts/ and markdown/ folders will stay local (not pushed)"
echo ""
