package com.userjourney.analytics.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Model representing insights generated by Amazon Nova context analysis
 */
public class NovaContextInsights {
    
    @JsonProperty("userId")
    private String userId;
    
    @JsonProperty("analysisText")
    private String analysisText;
    
    @JsonProperty("userIntent")
    private String userIntent;
    
    @JsonProperty("engagementLevel")
    private String engagementLevel;
    
    @JsonProperty("riskFactors")
    private List<String> riskFactors;
    
    @JsonProperty("personalizationOpportunities")
    private List<String> personalizationOpportunities;
    
    @JsonProperty("nextBestActions")
    private List<String> nextBestActions;
    
    @JsonProperty("interventionRecommendations")
    private List<String> interventionRecommendations;
    
    @JsonProperty("confidence")
    private double confidence;
    
    @JsonProperty("timestamp")
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime timestamp;
    
    @JsonProperty("success")
    private boolean success;
    
    @JsonProperty("errorMessage")
    private String errorMessage;
    
    // Default constructor
    public NovaContextInsights() {}
    
    // Builder pattern
    public static Builder builder() {
        return new Builder();
    }
    
    public static class Builder {
        private NovaContextInsights insights = new NovaContextInsights();
        
        public Builder userId(String userId) {
            insights.userId = userId;
            return this;
        }
        
        public Builder analysisText(String analysisText) {
            insights.analysisText = analysisText;
            return this;
        }
        
        public Builder userIntent(String userIntent) {
            insights.userIntent = userIntent;
            return this;
        }
        
        public Builder engagementLevel(String engagementLevel) {
            insights.engagementLevel = engagementLevel;
            return this;
        }
        
        public Builder riskFactors(List<String> riskFactors) {
            insights.riskFactors = riskFactors;
            return this;
        }
        
        public Builder personalizationOpportunities(List<String> personalizationOpportunities) {
            insights.personalizationOpportunities = personalizationOpportunities;
            return this;
        }
        
        public Builder nextBestActions(List<String> nextBestActions) {
            insights.nextBestActions = nextBestActions;
            return this;
        }
        
        public Builder interventionRecommendations(List<String> interventionRecommendations) {
            insights.interventionRecommendations = interventionRecommendations;
            return this;
        }
        
        public Builder confidence(double confidence) {
            insights.confidence = confidence;
            return this;
        }
        
        public Builder timestamp(LocalDateTime timestamp) {
            insights.timestamp = timestamp;
            return this;
        }
        
        public Builder success(boolean success) {
            insights.success = success;
            return this;
        }
        
        public Builder errorMessage(String errorMessage) {
            insights.errorMessage = errorMessage;
            return this;
        }
        
        public NovaContextInsights build() {
            return insights;
        }
    }
    
    // Getters and Setters
    public String getUserId() {
        return userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    public String getAnalysisText() {
        return analysisText;
    }
    
    public void setAnalysisText(String analysisText) {
        this.analysisText = analysisText;
    }
    
    public String getUserIntent() {
        return userIntent;
    }
    
    public void setUserIntent(String userIntent) {
        this.userIntent = userIntent;
    }
    
    public String getEngagementLevel() {
        return engagementLevel;
    }
    
    public void setEngagementLevel(String engagementLevel) {
        this.engagementLevel = engagementLevel;
    }
    
    public List<String> getRiskFactors() {
        return riskFactors;
    }
    
    public void setRiskFactors(List<String> riskFactors) {
        this.riskFactors = riskFactors;
    }
    
    public List<String> getPersonalizationOpportunities() {
        return personalizationOpportunities;
    }
    
    public void setPersonalizationOpportunities(List<String> personalizationOpportunities) {
        this.personalizationOpportunities = personalizationOpportunities;
    }
    
    public List<String> getNextBestActions() {
        return nextBestActions;
    }
    
    public void setNextBestActions(List<String> nextBestActions) {
        this.nextBestActions = nextBestActions;
    }
    
    public List<String> getInterventionRecommendations() {
        return interventionRecommendations;
    }
    
    public void setInterventionRecommendations(List<String> interventionRecommendations) {
        this.interventionRecommendations = interventionRecommendations;
    }
    
    public double getConfidence() {
        return confidence;
    }
    
    public void setConfidence(double confidence) {
        this.confidence = confidence;
    }
    
    public LocalDateTime getTimestamp() {
        return timestamp;
    }
    
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }
    
    public boolean isSuccess() {
        return success;
    }
    
    public void setSuccess(boolean success) {
        this.success = success;
    }
    
    public String getErrorMessage() {
        return errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
    
    @Override
    public String toString() {
        return "NovaContextInsights{" +
                "userId='" + userId + '\'' +
                ", userIntent='" + userIntent + '\'' +
                ", engagementLevel='" + engagementLevel + '\'' +
                ", confidence=" + confidence +
                ", success=" + success +
                ", timestamp=" + timestamp +
                '}';
    }
}