apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: true
      alertmanagerUid: "alertmanager"
    secureJsonData: {}

  - name: Prometheus-CloudWatch
    type: prometheus
    access: proxy
    url: http://cloudwatch-exporter:9106
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "60s"
      queryTimeout: "120s"
      httpMethod: "GET"
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      timeout: "60s"
    secureJsonData: {}

  - name: Alertmanager
    type: alertmanager
    uid: "alertmanager"
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: true
    jsonData:
      implementation: "prometheus"
    secureJsonData: {}